### ISSUE TITLE
Ogre misnamed ?

### ISSUE THREAD

**Issue by fauxilla** [Sauloxd/font-ascii#1]
Thanks for a rad package :)

Ogre from this package isn't the same as the one on [patorjk](http://patorjk.com/software/taag/#p=display&f=Ogre&t=not%20the%20same).

No biggie, just saying.

**Comment by Sauloxd** [comment]
Wow, It's been so long, I'm very sorry for that!
I'm probably the worst maintainer ever! hahaha

Just so you know, there is a major flaw in this project, because I only scrapped the uppercase version of the letters D: an d by now I completely lost my scrapper script!

![image](https://user-images.githubusercontent.com/11878589/67535881-0b3e8d00-f6ab-11e9-87d4-bf0ab9bb8232.png)
Up is 'not equal'
Down is 'NOT EQUAL'.

I'll create an issue to address this enhancement!
